name: Simple Pipeline

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build
      run: echo "Building..."
            
    
      
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "Testing..."
  
  pre-prod:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploying..."

  production:
    needs: [ build, pre-prod ]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploying..."    
