name: Simple Pipeline

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print Hello World
      run: echo "Hello World -build"

  test:
    runs-on: ubuntu-latest
    needs: build
     
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print Hello World
      run: echo "Hello World -test"
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print Hello World
      run: echo "Hello World -deploy"
