name: Simple Pipeline

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build
      run: echo "Building..."
      
    - name: Test
      run: echo "Testing..."
      
    - name: Deploy
      run: echo "Deploying..."
      
  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - name: Deploy to Production
      run: echo "Deploying to production..."
