name: Adding the Keys

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
  
#env:
# SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "add-keys"
  add-keys:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
    #runs-on: common
    # environment:
      #name: ${{ github.event.inputs.env }}
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
       # with:
        #  ref: ${{ github.event.inputs.env }}
      - run: pwd    
      # Runs a single command using the runner's shell
      - name: Run task.sh 
        run: |
          chmod +x /yuvraj/practice/task.sh
          bash /yuvraj/practice/task.sh
