name: New pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:      
      env:
        description: 'Choose Your Environment'
        required: true
        type: string
        default: 'devops'
        options:
          - devops
          - dev
          - stage
          - preprod
          - production
      cluster:
        type: choice
        description: 'Choose your cluster'
        options:
        - odoo
        - keyclock
        - swf-jitips
        required: true
#env:
 #SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "add-keys"
  add-keys:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    
    #runs-on: common
    # environment:
      #name: ${{ github.event.inputs.env }}
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
       # with:
        #  ref: ${{ github.event.inputs.env }}
      - run: pwd 
      
    #  - name: download config file
     #   run: |
      #    cd deploy/${{ github.event.inputs.cluster }}
       #   touch ${{ github.event.inputs.env }}_config_${{ github.event.inputs.cluster }}.yaml 
        #  scw k8s kubeconfig get $(scw k8s cluster list -c /root/.config/scw/config.yaml | awk '/${{ github.event.inputs.env }}-${{ github.event.inputs.cluster }}/' | awk '{print $1}') -c /root/.config/scw/config.yaml >> ${{ github.event.inputs.env }}_config_${{ github.event.inputs.cluster }}.yaml 
    
    #  - name: fatching values
     #   run: |
      #    cd deploy/${{ github.event.inputs.cluster }}
       #   bash deploy-${{ github.event.inputs.cluster }}.sh -e ${{ github.event.inputs.env }} 

      - name: Set up SSH
       # uses: webfactory/ssh-agent@v0.5.3
       # with:
       #   ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: run a script
        run: |
          ssh -i yuvraj@172.31.140.23 /home/ubuntu/local-key
          bash /home/yuvraj/practice/task.sh
            
      
