name: Tunnel Token
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Choose Your Environment
        options:
        - devops
        - dev
        - stage
        - preprod
        - production
        - test
      
      cluster:
        type: choice
        description: Name of your Cluster
        options:
         - odoo
         - keycloak 
         - swf-jitips
      
      token:
        required: true
        #type: string
        description: "Token to use for the tunnel"      


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.env }}  
      - name: Print Token
        run: |
          echo "Token provided by user: ${{ github.event.inputs.token }}"
      

      # - name: Add Scaleway CLI
      #   run: echo y | scw init secret-key=${{ secrets.SCW_SECRET_KEY }}  access-key=${{ secrets.SCW_ACCESS_KEY }} project-id=${{ secrets.PROJECT_ID }} organization-id=${{ secrets.ORGANIZATION_ID }} region=fr-par with-ssh-key=false -c /root/.config/scw/config.yaml
  

      # - name: Download the Kube Config file
      #   run: |
      #     mkdir -p files/${{ github.event.inputs.cluster }}
      #     cd files/${{ github.event.inputs.cluster }}
      #     touch ${{ github.event.inputs.env }}_config_${{ github.event.inputs.cluster }}.yaml 
      #     scw k8s kubeconfig get $(scw k8s cluster list -c /root/.config/scw/config.yaml | awk '/${{ github.event.inputs.env }}-${{ github.event.inputs.cluster }}/' | awk '{print $1}') -c /root/.config/scw/config.yaml >> ${{ github.event.inputs.env }}_config_${{ github.event.inputs.cluster }}.yaml 
    

      - name: Adding the token
        run: |
          sed 's/var_token/${{ github.event.inputs.token }}/' ./tunnel.yaml 

      # - name: Creating Tunnel in the Cluster 
      #   run: |
      #     cd files
      #     kubectl apply -f tunnel.yaml --kubeconfig ${{ github.event.inputs.cluster }}/${{ github.event.inputs.env }}_config_${{ github.event.inputs.cluster }}.yaml
